# Assignment 0

### <span style="color:chocolate"> Submission requirements </span>

Your work will not be graded if your notebook doesn't include output. In other words, <span style="color:red"> make sure to rerun your notebook before submitting to Gradescope </span> (Note: if you are using Google Colab: go to Edit > Notebook Settings  and uncheck Omit code cell output when saving this notebook, otherwise the output is not printed).

Additional points may be deducted if these requirements are not met:

    
* Comment your code;
* Each graph should have a title, labels for each axis, and (if needed) a legend. Each graph should be understandable on its own;
* Try and minimize the use of the global namespace (meaning, keep things inside functions).
---

### Import libraries

In [1]:
import numpy as np
np.random.seed(seed=1)

---
### <span style="color:chocolate">Exercise 1:</span> Homogenous data types (10 points)

1. Create a numpy array (my_array1) containing only integer values. Print the shape of the array and the type of its elements;
2. Create another numpy array (my_array2) containing a mix of integer and string values. Print the shape of the array and the type of its elements. What explains the datatype of the array?

In [2]:
my_array1 = np.array([1,2,3,4,5])
print(f"my_array1 is a {type(my_array1)}")
print(f"my_array1 contains {my_array1.size} of {my_array1.dtype.name}")
print(f"my_array1.shape = {my_array1.shape}")
print("\n")

my_array2 = np.array([1,"m",2,"g"])
print(f"my_array2 is a {type(my_array1)}")
print(f"my_array2 contains {my_array2.size} of {my_array2.dtype.name}")
print(f"my_array2.shape = {my_array2.shape}")
print("\n")

explanation = "When given an array of mixed data types, numpy uses upcasting to determine the most general dtype to use for the entire array."
print(explanation)

my_array1 is a <class 'numpy.ndarray'>
my_array1 contains 5 of int64
my_array1.shape = (5,)


my_array2 is a <class 'numpy.ndarray'>
my_array2 contains 4 of str672
my_array2.shape = (4,)


When given an array of mixed data types, numpy uses upcasting to determine the most general dtype to use for the entire array.


---
#### <span style="color:chocolate">Exercise 2:</span> The size attribute (10 points)

Create a numpy array (my_array3) and print its shape, size, and data type. What does size represent?

In [3]:
my_array3 = np.arange(9)
print(f"my_array3 is a {type(my_array3)}")
print(f"my_array3.size = {my_array3.size}")
print(f"my_array3.shape = {my_array3.shape}")
print(f"my_array3.dtype is {my_array3.dtype.name}")

print("\nReshaping my_array3...")
my_array3 = my_array3.reshape(3,3)
print(f"my_array3.size = {my_array3.size}")
print(f"my_array3.shape = {my_array3.shape}")
print(f"my_array3.dtype is {my_array3.dtype.name}")

explanation = "\nnp.size returns the product of the array's dimensions."
print(explanation)

my_array3 is a <class 'numpy.ndarray'>
my_array3.size = 9
my_array3.shape = (9,)
my_array3.dtype is int64

Reshaping my_array3...
my_array3.size = 9
my_array3.shape = (3, 3)
my_array3.dtype is int64

np.size returns the product of the array's dimensions.


---
#### <span style="color:chocolate">Exercise 3:</span> Tabular data layout (10 points)

Create a tabular data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:
* the first input is num_samples, and
* the second input is num_features. 

Print the shape of the array.

In [4]:
# already defined first and second inputs
num_samples = 100
num_features = 17

my_array6 = np.random.random(size=(num_samples, num_features))
print(f"my_array6.shape = {my_array6.shape}")

my_array6.shape = (100, 17)


---
#### <span style="color:chocolate">Exercise 4:</span> Image data layout (10 points)

Create an image data layout using the numpy method <span style="color:chocolate">np.random.random()</span>, where:

* the first input is num_images;
* the second input is num_rows;
* the third input is num_cols;
* the fourth input is num_channels.

Print the shape of the array.

In [5]:
# already defined inputs
num_images = 100
num_rows = 256
num_cols = 256
num_channels = 3 #(RGB)

my_array5 = np.random.random(size=(num_images, num_rows, num_cols, num_channels))
print(f"my_array5.shape = {my_array5.shape}")

my_array5.shape = (100, 256, 256, 3)


---
#### <span style="color:chocolate">Exercise 5: </span>Mathematical operations on numpy arrays (15 points)

Create a (3, 2) numpy array (you can name it my_array4) containing only integer values. Perform the following tasks:

1. Print the shape of the array;
2. Print the sum of all elements (hint: the axis argument is set to None);
3. Print the sum of all elements by column;
3. Print the sum of all elements by row and change the type of the resulting array elements to float;
5. Print the first row of the array;
6. Print the second row of the array;
7. Select the element at position (1, 0);
8. Modify the element at position (2, 1) by setting its value to 10 and print the array again;
9. Loop over all the elements in the array. Print the output.

In [6]:
my_array4 = np.arange(6).reshape(3,2)
print(f"{my_array4=}")
print(f"1. my_array4.shape = {my_array4.shape}")
print(f"2. my_array4.sum = {my_array4.sum(axis=None)}")
print(f"3. sum of cols of my_array4 = {my_array4.sum(axis=0)}")
print(f"4. sum of rows of my_array4 as float = {my_array4.sum(axis=1, dtype='float64')}")
print(f"5. first row of my_array4 = {my_array4[0]}")
print(f"6. second row of my_array4 = {my_array4[1]}")
print(f"7. element (1,0) of my_array4 = {my_array4[1][0]}")
print("Setting element (2,1) to 10...")
my_array4[2][1]=10
print(f"8. {my_array4=}")
print("9.")
for r in range(len(my_array4)):
    for c in range(len(my_array4[0])):
        print(f"(r={r}, c={c}) {my_array4[r][c]=}")

my_array4=array([[0, 1],
       [2, 3],
       [4, 5]])
1. my_array4.shape = (3, 2)
2. my_array4.sum = 15
3. sum of cols of my_array4 = [6 9]
4. sum of rows of my_array4 as float = [1. 5. 9.]
5. first row of my_array4 = [0 1]
6. second row of my_array4 = [2 3]
7. element (1,0) of my_array4 = 2
Setting element (2,1) to 10...
8. my_array4=array([[ 0,  1],
       [ 2,  3],
       [ 4, 10]])
9.
(r=0, c=0) my_array4[r][c]=np.int64(0)
(r=0, c=1) my_array4[r][c]=np.int64(1)
(r=1, c=0) my_array4[r][c]=np.int64(2)
(r=1, c=1) my_array4[r][c]=np.int64(3)
(r=2, c=0) my_array4[r][c]=np.int64(4)
(r=2, c=1) my_array4[r][c]=np.int64(10)


You can find more examples here: https://numpy.org/doc/stable/reference/routines.math.html

---
#### <span style="color:chocolate">Exercise 6:</span> Create arrays (15 points)

1. Create and print a (3,2) numpy array of pixel values between 0 and 1.
2. Create and print a (27,) numpy array representing years from 1991 to 2017
3. Create and print a (3, 5, 10) numpy array of zeros
4. Create and print a (3, 5, 10) numpy array of ones
5. Create and print an array with a constant value (let's say 5) using np.ones()
6. Create and print an array with random numbers drawn from a normal distribution with mean 0 and standard deviation 1. Set the sample size to 10.


In [7]:
print(f"1.\n{np.random.random(size=(3,2))=}")
print(f"2.\n{np.arange(1991,2018)=}")
print(f"3.\n{np.zeros(shape=(3,5,10))=}")
print(f"4.\n{np.ones(shape=(3,5,10))=}")
print(f"5.\n{np.ones(shape=(3,5,10))*5=}")
print(f"6.\n{np.random.normal(loc=0, scale=1, size=10)}")

1.
np.random.random(size=(3,2))=array([[0.28999571, 0.50818013],
       [0.47655793, 0.57281228],
       [0.53403895, 0.66869277]])
2.
np.arange(1991,2018)=array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])
3.
np.zeros(shape=(3,5,10))=array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

---
#### <span style="color:chocolate">Exercise 7:</span> Reshape arrays (10 points)

Consider the following array:

In [8]:
years = np.arange(1991, 2018, 1)
print(years.shape)

(27,)


Perform the following operations on this array:
    
1. Create 3 nested arrays, each of size (3, 3). Call this array years_3d (Hint: use np.reshape());
2. Convert the years_3d array to a flat 1D array. Call this array years_1d (Hint: use np.flatten());
3. Add a new dimension (axis=0) to the years_1d array. Call this array years_2d (Hint: use np.expand_dims());
4. Remove the first axis from years_2d array. Call this array years_1d (Hint: use np.squeeze()).

For each exercise print the array and its shape.

In [9]:
years_3d = years.reshape((3,3,3))
print(f"1.\n{years_3d=}\n{years_3d.shape=}\n")
years_1d = years_3d.flatten()
print(f"2.\n{years_1d=}\n{years_1d.shape=}\n")
years_2d = np.expand_dims(years_1d, axis=0)
print(f"3.\n{years_2d=}\n{years_2d.shape=}\n")
years_1d = np.squeeze(years_2d, axis=0)
print(f"4.\n{years_1d=}\n{years_1d.shape=}")

1.
years_3d=array([[[1991, 1992, 1993],
        [1994, 1995, 1996],
        [1997, 1998, 1999]],

       [[2000, 2001, 2002],
        [2003, 2004, 2005],
        [2006, 2007, 2008]],

       [[2009, 2010, 2011],
        [2012, 2013, 2014],
        [2015, 2016, 2017]]])
years_3d.shape=(3, 3, 3)

2.
years_1d=array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])
years_1d.shape=(27,)

3.
years_2d=array([[1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
        2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
        2013, 2014, 2015, 2016, 2017]])
years_2d.shape=(1, 27)

4.
years_1d=array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])
years_1d.shape=(27,)


---
#### <span style="color:chocolate">Exercise 8:</span> Joining arrays (10 points)

Provide 8 examples that use the methods <span style="color:cornflowerBlue">np.concatenate()</span> and <span style="color:cornflowerBlue">np.stack()</span>. Note: create 4 examples using each method.

In [10]:
print("np.concatenate")
print(f"1. {np.concatenate((years_1d, years_1d), dtype='float64')}")
print(f"2. {np.concatenate((years_3d, np.random.random((3,3,3))))}")
print(f"3. {np.concat((np.zeros(4), np.ones(4)), axis=0)}")
print(f"4. {np.concat((years_2d.reshape((3,3,3)),years_1d.reshape((3,3,3))),axis=1)}")

print("\nnp.stack")
print(f"5. {np.stack((years_1d, years_1d), dtype='float64')}")
print(f"6. {np.stack((years_3d, np.random.random((3,3,3))))}")
print(f"7. {np.stack((np.zeros(4), np.ones(4)), axis=0)}")
print(f"8. {np.stack((years_2d.reshape((3,3,3)),years_1d.reshape((3,3,3))),axis=1)}")


np.concatenate
1. [1991. 1992. 1993. 1994. 1995. 1996. 1997. 1998. 1999. 2000. 2001. 2002.
 2003. 2004. 2005. 2006. 2007. 2008. 2009. 2010. 2011. 2012. 2013. 2014.
 2015. 2016. 2017. 1991. 1992. 1993. 1994. 1995. 1996. 1997. 1998. 1999.
 2000. 2001. 2002. 2003. 2004. 2005. 2006. 2007. 2008. 2009. 2010. 2011.
 2012. 2013. 2014. 2015. 2016. 2017.]
2. [[[1.99100000e+03 1.99200000e+03 1.99300000e+03]
  [1.99400000e+03 1.99500000e+03 1.99600000e+03]
  [1.99700000e+03 1.99800000e+03 1.99900000e+03]]

 [[2.00000000e+03 2.00100000e+03 2.00200000e+03]
  [2.00300000e+03 2.00400000e+03 2.00500000e+03]
  [2.00600000e+03 2.00700000e+03 2.00800000e+03]]

 [[2.00900000e+03 2.01000000e+03 2.01100000e+03]
  [2.01200000e+03 2.01300000e+03 2.01400000e+03]
  [2.01500000e+03 2.01600000e+03 2.01700000e+03]]

 [[5.31221554e-01 2.37281923e-01 8.72005547e-01]
  [9.89537574e-01 9.44649530e-01 2.59047822e-02]
  [2.41036029e-01 2.09232762e-01 6.91936843e-01]]

 [[7.02465192e-01 5.92360703e-01 2.85496978e-01]
  [9

---
#### <span style="color:chocolate">Numpy broadcasting</span> 

The term broadcasting describes how NumPy treats arrays during arithmetic operations. You can find more here:  https://numpy.org/doc/stable/user/basics.broadcasting.html

In [11]:
# multiplying an array with a scalar
years = np.arange(1991, 2018, 1)
years * 1

array([1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017])

In [12]:
# adding a scalar
years + 2

array([1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019])

In [13]:
# many arithmetic operations are applied element wise on a pair of arrays
a = np.arange(3)
print('Array a:', a)
b = np.arange(3)
print('Array b:', b)
print('Sum of a and b:', a+b)

Array a: [0 1 2]
Array b: [0 1 2]
Sum of a and b: [0 2 4]


In [14]:
# another example
a = np.ones((3, 3))
print('Array a:', a)
b = np.arange(3)
print('\nArray b:', b)
print('\nSum of a and b:', a+b)

Array a: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array b: [0 1 2]

Sum of a and b: [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


---
#### <span style="color:chocolate">Exercise 9:</span> Numpy array standardization (10 points)

Consider the following (10, 4) array:

In [15]:
my_array = np.random.random((10, 4))
print('my_array shape: ', my_array.shape)
my_array

my_array shape:  (10, 4)


array([[0.06359069, 0.29458122, 0.29966852, 0.38003294],
       [0.66119897, 0.25088594, 0.47417998, 0.31791607],
       [0.1578268 , 0.74578781, 0.4648818 , 0.97938415],
       [0.07893171, 0.39555649, 0.38922361, 0.99142393],
       [0.71064371, 0.78614272, 0.9149905 , 0.30968276],
       [0.61087266, 0.54685109, 0.09937353, 0.84499208],
       [0.66970242, 0.96634253, 0.6866152 , 0.79079929],
       [0.59628123, 0.00668868, 0.38347787, 0.935465  ],
       [0.06119359, 0.83823729, 0.7621429 , 0.59478823],
       [0.48583373, 0.18892897, 0.34150298, 0.7686633 ]])

Peform the following operations on this array:
1. Compute and print the mean and std for each column (note: set keepdims=True for proper broadcasting).
2. Standardize and print the array and its shape using the mean and std you computed above.

In [16]:
print("1.")
mean = my_array.mean(keepdims=True)
std = my_array.std(keepdims=True)
print(f"Mean: {mean}")
print(f"Standard deviation: {std}")

print("\n2.")
standardized_array = (my_array-mean)/std
print(f"{standardized_array=}")
print(f"{standardized_array.shape=}")

1.
Mean: [[0.52113207]]
Standard deviation: [[0.28595486]]

2.
standardized_array=array([[-1.60004757, -0.7922609 , -0.77447031, -0.49343149],
       [ 0.48982173, -0.9450657 , -0.16419407, -0.71065763],
       [-1.27049868,  0.78563358, -0.19671032,  1.60253293],
       [-1.54639919, -0.43914478, -0.46129121,  1.6446367 ],
       [ 0.66273271,  0.92675694,  1.37734477, -0.73944998],
       [ 0.31382783,  0.08994083, -1.47491302,  1.13255641],
       [ 0.51955873,  1.55692565,  0.57870368,  0.94304122],
       [ 0.26280076, -1.79903709, -0.48138436,  1.44894523],
       [-1.60843038,  1.10893452,  0.84282823,  0.25757966],
       [-0.12344025, -1.16173268, -0.6281729 ,  0.86563042]])
standardized_array.shape=(10, 4)


----
#### <span style="color:chocolate">Additional practice question</span> (not graded)

Consider the following image:

In [17]:
my_image = np.arange(0, 1, 0.04).reshape(5,5)
print(my_image)
my_image.shape

[[0.   0.04 0.08 0.12 0.16]
 [0.2  0.24 0.28 0.32 0.36]
 [0.4  0.44 0.48 0.52 0.56]
 [0.6  0.64 0.68 0.72 0.76]
 [0.8  0.84 0.88 0.92 0.96]]


(5, 5)

Perform the following operations on this image (do not overwrite the original image):

1. Crop by using a border of size 1;
2. Crop by removing:
    * the first and the last two rows, and
    * the first and the last two columns;
3. Reverse the column order;
4. set to 0.5 elements divizible by 2.

In [18]:
def crop(image, pixels):
    rlen = len(image)
    clen = len(image[0])
    return image[pixels:rlen-pixels, pixels:clen-pixels]
print(f"1.\n{crop(my_image,1)}")
print(f"2.\n{crop(my_image,2)}")
print(f"3.\n{my_image[:,::-1]}")

1.
[[0.24 0.28 0.32]
 [0.44 0.48 0.52]
 [0.64 0.68 0.72]]
2.
[[0.48]]
3.
[[0.16 0.12 0.08 0.04 0.  ]
 [0.36 0.32 0.28 0.24 0.2 ]
 [0.56 0.52 0.48 0.44 0.4 ]
 [0.76 0.72 0.68 0.64 0.6 ]
 [0.96 0.92 0.88 0.84 0.8 ]]
